notifications:
  email:
    recipients:
      - travis-ci@bxlab.pl
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - next-release

language: bash

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required

addons:
  apt:
    packages:
      - openssl
      - curl

before_install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install shellcheck

after_success:
  - test $TRAVIS_PULL_REQUEST = false && git push

script:
  - shellcheck sslmerge
